/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto_de_venta.vistas;

/**
 *
 * @author jcm_0
 */
public class frmCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form frmCatalogo
     */
    public frmCatalogo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pancontenedor = new javax.swing.JPanel();
        panencabezado = new javax.swing.JPanel();
        btncerrar = new javax.swing.JButton();
        lbliconotitulo = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        sprtitulo = new javax.swing.JSeparator();
        pancontenido = new javax.swing.JPanel();
        sprbuscar = new javax.swing.JSeparator();
        scplistacatalogo = new javax.swing.JScrollPane();
        tbllistacatalogo = new javax.swing.JTable();
        sprcontenido = new javax.swing.JSeparator();
        lbliconobuscar = new javax.swing.JLabel();
        lblsubtitulolista = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        pannuevoproducto = new javax.swing.JPanel();
        pancontroles = new javax.swing.JPanel();
        lblclaveproducto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblrfcproveedor = new javax.swing.JLabel();
        lbldescripcionproducto = new javax.swing.JLabel();
        txtrfcproveedor = new javax.swing.JTextField();
        scpdescripcionproducto = new javax.swing.JScrollPane();
        txadescripcionproducto = new javax.swing.JTextArea();
        lblunidadmedida = new javax.swing.JLabel();
        lblcategoria = new javax.swing.JLabel();
        lblpreciocompra = new javax.swing.JLabel();
        lblprecioventa = new javax.swing.JLabel();
        cmbunidadmedida = new javax.swing.JComboBox<>();
        cmbcategoria = new javax.swing.JComboBox<>();
        txtpreciocompra = new javax.swing.JTextField();
        txtprecioventa = new javax.swing.JTextField();
        lblsubtitulonuevoproducto = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frmCatalogo"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        pancontenedor.setBackground(new java.awt.Color(255, 255, 255));
        pancontenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        panencabezado.setBackground(new java.awt.Color(0, 102, 153));

        btncerrar.setBackground(new java.awt.Color(0, 102, 153));
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto_de_venta/vistas/icons/icons8_Close_Window_48px.png"))); // NOI18N
        btncerrar.setToolTipText("");
        btncerrar.setBorder(null);
        btncerrar.setMaximumSize(new java.awt.Dimension(48, 48));
        btncerrar.setMinimumSize(new java.awt.Dimension(48, 48));
        btncerrar.setPreferredSize(new java.awt.Dimension(48, 48));
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        lbliconotitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto_de_venta/vistas/icons/icons8_Moleskine_64px_1.png"))); // NOI18N

        lbltitulo.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Catálogo de productos");

        sprtitulo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panencabezadoLayout = new javax.swing.GroupLayout(panencabezado);
        panencabezado.setLayout(panencabezadoLayout);
        panencabezadoLayout.setHorizontalGroup(
            panencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panencabezadoLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(lbliconotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sprtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panencabezadoLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(lbltitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panencabezadoLayout.setVerticalGroup(
            panencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbliconotitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panencabezadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panencabezadoLayout.createSequentialGroup()
                        .addComponent(lbltitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sprtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panencabezadoLayout.createSequentialGroup()
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pancontenido.setBackground(new java.awt.Color(255, 255, 255));

        tbllistacatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scplistacatalogo.setViewportView(tbllistacatalogo);

        lbliconobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto_de_venta/vistas/icons/icons8_Detective_64px.png"))); // NOI18N

        lblsubtitulolista.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblsubtitulolista.setText("Lista de productos");

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto_de_venta/vistas/icons/icons8_Edit_64px_1.png"))); // NOI18N

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto_de_venta/vistas/icons/icons8_Trash_Can_52px.png"))); // NOI18N

        txtbuscar.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        txtbuscar.setBorder(null);

        pannuevoproducto.setBackground(new java.awt.Color(255, 255, 255));

        pancontroles.setBackground(new java.awt.Color(255, 255, 255));

        lblclaveproducto.setText("Clave del producto");

        lblrfcproveedor.setText("RFC del proveedor");

        lbldescripcionproducto.setText("Descripción del producto");

        txadescripcionproducto.setColumns(20);
        txadescripcionproducto.setRows(5);
        scpdescripcionproducto.setViewportView(txadescripcionproducto);

        lblunidadmedida.setText("Unidad de medida");

        lblcategoria.setText("Categoría");

        lblpreciocompra.setText("Precio de compra");

        lblprecioventa.setText("Precio de venta");

        cmbunidadmedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblsubtitulonuevoproducto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblsubtitulonuevoproducto.setText("Nuevo producto");

        javax.swing.GroupLayout pancontrolesLayout = new javax.swing.GroupLayout(pancontroles);
        pancontroles.setLayout(pancontrolesLayout);
        pancontrolesLayout.setHorizontalGroup(
            pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancontrolesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsubtitulonuevoproducto)
                .addGap(43, 43, 43)
                .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pancontrolesLayout.createSequentialGroup()
                        .addComponent(lblclaveproducto)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(pancontrolesLayout.createSequentialGroup()
                        .addComponent(lblrfcproveedor)
                        .addGap(18, 18, 18)
                        .addComponent(txtrfcproveedor))
                    .addComponent(lbldescripcionproducto)
                    .addComponent(scpdescripcionproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblunidadmedida)
                    .addComponent(lblcategoria)
                    .addComponent(lblpreciocompra)
                    .addComponent(lblprecioventa))
                .addGap(18, 18, 18)
                .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbunidadmedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbcategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpreciocompra)
                    .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        pancontrolesLayout.setVerticalGroup(
            pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pancontrolesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pancontrolesLayout.createSequentialGroup()
                        .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblunidadmedida)
                            .addComponent(cmbunidadmedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcategoria)
                            .addComponent(cmbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpreciocompra)
                            .addComponent(txtpreciocompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblprecioventa)
                            .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(pancontrolesLayout.createSequentialGroup()
                        .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblclaveproducto)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblsubtitulonuevoproducto))
                        .addGap(18, 18, 18)
                        .addGroup(pancontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblrfcproveedor)
                            .addComponent(txtrfcproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbldescripcionproducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scpdescripcionproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto_de_venta/vistas/icons/icons8_Save_64px.png"))); // NOI18N

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto_de_venta/vistas/icons/icons8_Cancel_64px_1.png"))); // NOI18N

        javax.swing.GroupLayout pannuevoproductoLayout = new javax.swing.GroupLayout(pannuevoproducto);
        pannuevoproducto.setLayout(pannuevoproductoLayout);
        pannuevoproductoLayout.setHorizontalGroup(
            pannuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannuevoproductoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(pancontroles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannuevoproductoLayout.setVerticalGroup(
            pannuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannuevoproductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pancontroles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pannuevoproductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pannuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pancontenidoLayout = new javax.swing.GroupLayout(pancontenido);
        pancontenido.setLayout(pancontenidoLayout);
        pancontenidoLayout.setHorizontalGroup(
            pancontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sprcontenido)
            .addGroup(pancontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pancontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pancontenidoLayout.createSequentialGroup()
                        .addComponent(lblsubtitulolista)
                        .addGap(124, 124, 124)
                        .addComponent(lbliconobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pancontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pancontenidoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sprbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pancontenidoLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pancontenidoLayout.createSequentialGroup()
                        .addGroup(pancontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pannuevoproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scplistacatalogo))
                        .addContainerGap())))
        );
        pancontenidoLayout.setVerticalGroup(
            pancontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pancontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pannuevoproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pancontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pancontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pancontenidoLayout.createSequentialGroup()
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sprbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbliconobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblsubtitulolista))
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scplistacatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pancontenedorLayout = new javax.swing.GroupLayout(pancontenedor);
        pancontenedor.setLayout(pancontenedorLayout);
        pancontenedorLayout.setHorizontalGroup(
            pancontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panencabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pancontenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pancontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pancontenedorLayout.setVerticalGroup(
            pancontenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pancontenedorLayout.createSequentialGroup()
                .addComponent(panencabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pancontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pancontenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pancontenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cmbcategoria;
    private javax.swing.JComboBox<String> cmbunidadmedida;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblclaveproducto;
    private javax.swing.JLabel lbldescripcionproducto;
    private javax.swing.JLabel lbliconobuscar;
    private javax.swing.JLabel lbliconotitulo;
    private javax.swing.JLabel lblpreciocompra;
    private javax.swing.JLabel lblprecioventa;
    private javax.swing.JLabel lblrfcproveedor;
    private javax.swing.JLabel lblsubtitulolista;
    private javax.swing.JLabel lblsubtitulonuevoproducto;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblunidadmedida;
    private javax.swing.JPanel pancontenedor;
    private javax.swing.JPanel pancontenido;
    private javax.swing.JPanel pancontroles;
    private javax.swing.JPanel panencabezado;
    private javax.swing.JPanel pannuevoproducto;
    private javax.swing.JScrollPane scpdescripcionproducto;
    private javax.swing.JScrollPane scplistacatalogo;
    private javax.swing.JSeparator sprbuscar;
    private javax.swing.JSeparator sprcontenido;
    private javax.swing.JSeparator sprtitulo;
    private javax.swing.JTable tbllistacatalogo;
    private javax.swing.JTextArea txadescripcionproducto;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtpreciocompra;
    private javax.swing.JTextField txtprecioventa;
    private javax.swing.JTextField txtrfcproveedor;
    // End of variables declaration//GEN-END:variables
}
